trigger: none

parameters:
  - name: DeployTo
    displayName: 'Select environment to deploy secrets for'
    type: string
    values:
      - dev
      - uat
      - ppd
      - prd
    default: dev

stages:
  - template: ../secrets/environments.yml
    parameters:
      deployTemplatePath: ../secrets/yaml/deploy.yml
      projectName: '<Fill Me In>'  ##Update if you're using a different project name in folder structure <Fill Me In>
      projectPath: 'secrets'  ##Update if you're using a different deployment resources name in folder structure
      DeployTo: ${{ parameters.DeployTo }}