parameters:
- name: deployTemplatePath
  default: ''
- name: projectName
  default: ''
- name: projectPath
  default: ''
- name: DeployTo
  default: ''

stages:
  - ${{ if eq(parameters.DeployTo, 'dev') }}:
      - stage: DEV
        displayName: DEV
        jobs:
          - template: '${{ parameters.deployTemplatePath }}'
            parameters:
              environment: 'dev'
              agentPool: '<Fill Me In>'
              serviceConnection: '<Fill Me In>'
              environmentVariableGroup: '${{ parameters.projectName }}-${{ parameters.projectPath }}-dev'
              projectName: '${{ parameters.projectName }}'
              projectPath: '${{ parameters.projectPath }}'
              keyvaultName: '<Fill Me In>'

  # - ${{ if eq(parameters.DeployTo, 'uat') }}:
  #     - stage: UAT
  #       displayName: UAT
  #       jobs:
  #         - template: '${{ parameters.deployTemplatePath }}'
  #           parameters:
  #             environment: 'uat'
  #             agentPool: '<Fill Me In>'
  #             serviceConnection: '<Fill Me In>'
  #             environmentVariableGroup: '${{ parameters.projectName }}-${{ parameters.projectPath }}-uat'
  #             projectName: '${{ parameters.projectName }}'
  #             projectPath: '${{ parameters.projectPath }}'
  #             keyvaultName: '<Fill Me In>'

  # - ${{ if eq(parameters.DeployTo, 'ppd') }}:
  #     - stage: PPD
  #       displayName: PPD
  #       jobs:
  #         - template: '${{ parameters.deployTemplatePath }}'
  #           parameters:
  #             environment: 'ppd'
  #             agentPool: '<Fill Me In>'
  #             serviceConnection: '<Fill Me In>'
  #             environmentVariableGroup: '${{ parameters.projectName }}-${{ parameters.projectPath }}-ppd'
  #             projectName: '${{ parameters.projectName }}'
  #             projectPath: '${{ parameters.projectPath }}'
  #             keyvaultName: '<Fill Me In>'

  # - ${{ if eq(parameters.DeployTo, 'prd') }}:
  #     - stage: PRD
  #       displayName: PRD
  #       jobs:
  #         - template: '${{ parameters.deployTemplatePath }}'
  #           parameters:
  #             environment: 'prd'
  #             agentPool: '<Fill Me In>'
  #             serviceConnection: '<Fill Me In>'
  #             environmentVariableGroup: '${{ parameters.projectName }}-${{ parameters.projectPath }}-prd'
  #             projectName: '${{ parameters.projectName }}'
  #             projectPath: '${{ parameters.projectPath }}'
  #             keyvaultName: '<Fill Me In>'