parameters:
- name: serviceConnection
  default: ''
- name: deploymentParameters
  default: ''
- name: keyvaultName
  default: ''
- name: deploymentName
  default: ''

steps:
  - task: AzureCLI@2
    displayName: ${{ parameters.deploymentName }}
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $KeyVaultName = "${{ parameters.keyvaultName }}"
        $paramString = "${{ parameters.deploymentParameters }}"
        $paramPairs = $paramString -split '\s+' | Where-Object { $_ -match '=' }
        foreach ($pair in $paramPairs) {
          $splitPair = $pair -split '=', 2
          $name = $splitPair[0]
          $value = $splitPair[1]
          if ($value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
          }
          if (![string]::IsNullOrEmpty($value)) {
            Write-Host "Uploading $name to Key Vault"
            if ($value -match '\\[nt\\]') {
                az keyvault secret set --vault-name $KeyVaultName --name $name --value "`"$value`""
              } else {
                az keyvault secret set --vault-name $KeyVaultName --name $name --value "$value"
              }
          } else {
            Write-Host "$name is not set or is empty, skipping."
          }
        }