parameters:
  - name: environment
    default: ""
  - name: environmentVariableGroup
    default: ""
  - name: agentPool
    default: ""
  - name: serviceConnection
    default: ""
  - name: projectName
    default: ""
  - name: projectPath
    default: ""
  - name: keyvaultName
    default: ""


jobs:
  - job: DeploySecrets
    displayName: "Deploy ${{ parameters.projectPath }} ${{ parameters.projectName }} pipeline"
    pool:
      name: ${{ parameters.agentPool }}
      demands: Agent.Alias -equals 'ubuntu-latest'
    variables:
      - group: ${{ parameters.environmentVariableGroup }}
      - template: secretsmap.yml
    steps:
      - template: ../../../templates/yaml/deploy/deploy-secrets-template.yml
        parameters:
          deploymentName: "Deploy ${{ parameters.projectPath }} for ${{ parameters.projectName }} ${{ parameters.environment }}"
          serviceConnection: ${{parameters.serviceConnection}}
          keyvaultName: ${{ parameters.keyvaultName}}
          deploymentParameters: "$(deploymentParameters)"

      - template: ../../../templates/yaml/deploy/clean-list-secrets-template.yml
        parameters:
          deploymentName: "List secrets that will be deleted"
          serviceConnection: ${{parameters.serviceConnection}}
          keyvaultName: ${{ parameters.keyvaultName}}
          deploymentParameters: "$(deploymentParameters)"

  - job: AwaitApproval
    displayName: "Manual Approval - Proceed to Delete?"
    dependsOn: DeploySecrets
    pool: server
    steps:
      - task: ManualValidation@0
        displayName: 'Await Manual Approval'
        inputs:
          instructions: 'Please review the secrets to be deleted and approve to continue.'
          onTimeout: 'reject'
          timeout: '1d'

  - job: CleanSecrets
    displayName: "Cleaning ${{ parameters.projectPath }} for ${{ parameters.projectName }} ${{ parameters.environment }}"
    dependsOn: AwaitApproval
    condition: eq(dependencies.AwaitApproval.result, 'Succeeded')
    pool:
      name: ${{ parameters.agentPool }}
      demands: Agent.Alias -equals 'ubuntu-latest'
    variables:
      - group: ${{ parameters.environmentVariableGroup }}
      - template: secretsmap.yml
    steps:
      - template: ../../../templates/yaml/deploy/clean-delete-secrets-template.yml
        parameters:
          deploymentName: "Delete ${{ parameters.projectPath }} ${{ parameters.projectName }} ${{ parameters.environment }}"
          serviceConnection: ${{parameters.serviceConnection}}
          keyvaultName: ${{ parameters.keyvaultName}}
          deploymentParameters: "$(deploymentParameters)"